# Generated by Django 2.1.2 on 2018-10-31 13:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_remove_user_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='last_latitude',
        ),
        migrations.AddField(
            model_name='user',
            name='last_longitude',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
