# Generated by Django 2.1.4 on 2018-12-10 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20181031_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_latitude',
            new_name='monitoring_station',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_longitude',
            new_name='phone_number',
        ),
    ]
